### ISSUE TITLE
jsonp issue when switching to webpack 5

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#303]
## Reproduce

1. build and serve app [commit](https://github.com/teamdigitale/dati-semantic-frontend/commit/a983243042c2637bf166e5c700d00f0aacbebe91) [docker image](https://github.com/teamdigitale/dati-semantic-frontend/pkgs/container/dati-semantic-frontend/50966053?tag=20221116-794-a983243)

```
git checkout a983243042c2637bf166e5c700d00f0aacbebe91
docker-compose down
docker-compose up --build react-app

# When the container is up, visit
google-chrome http://localhost:7001
```

## I Expect

- show page

## Instead
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (<anonymous>)
    at runtime.js:747:3
    at main.4e2b1ba6.js:2:150124
    at 21543 (main.4e2b1ba6.js:2:150152)
    at t (bootstrap:18:32)
    at d (jsonp chunk loading:76:13)
    at Array.f [as push] (jsonp chunk loading:125:9)
    at main.4e2b1ba6.js:2:59
```

**Comment by ioggstream** [comment]
Apparently, the issue remains even when setting

```
IMAGE_INLINE_SIZE_LIMIT=0
INLINE_RUNTIME_CHUNK=false
```

**Comment by ioggstream** [comment]
close via #311
